module.exports = {
  CONFIG_KEY_SCANNING_TIMEOUT: "scanning_timeout",
  CONFIG_KEY_POLL_INTERVAL: "poll_interval",
  CONFIG_KEY_HAP_INTERACTION_TIMEOUT: "hap_interaction_timeout",
  CONFIG_KEY_ALLOWED_DEVICES: "allowed_devices",
  DEFAULT_HAP_INTERACTION_TIMEOUT: 1.5 * 60,
  DEFAULT_POLL_INTERVAL: 5 * 60,
  DEFAULT_SCANNING_TIMEOUT: 8,
  POSITION_UPDATE_INTERVAL: 2 * 60,
  MISSING_DEVICES_SCANNING_TIMEOUT: 5,
  HAP_NO_INTERACTION_GRACE_PERIOD: 5,
  MINIMUM_POLL_INTERVAL: 5,
}
